### ISSUE TITLE
Default initialization of struct members

### ISSUE THREAD

**Issue by koliyo** [migueldeicaza/SwiftGodot#238] opened 2023-11-17 08:27 UTC
There is some kind of problem with struct members that are not explicitly initialized. I get a crash with the following:

```swift
@Godot
class MyNode: Node2D {
  let surface = SurfaceTool()
  let edgeMesh = MeshInstance2D()

  var foo: Vector2
}
```

due to the `foo` member not being initialized. If I explicitly initialize it it does no longer crash:

```swift
@Godot
class MyNode: Node2D {
  let surface = SurfaceTool()
  let edgeMesh = MeshInstance2D()

  var foo = Vector2()
}
```

The result should be the same in both cases, since the member is a struct, and has a default initializer (?). Also note, that for some reason I need the other members to get the crash in this example, if I remove them the crash also disappear.

**Comment by tishin** [comment] 2023-11-17 11:30
Before #234 the expanded code of the first case looked like this, and it didn't compile because of uninitialized property:
```swift
class CustomNode: Node2D {
    let surface = SurfaceTool()
    let edgeMesh = MeshInstance2D()

    var foo: Vector2
    
    required init(nativeHandle _: UnsafeRawPointer) {
        fatalError("init(nativeHandle:) called, it is a sign that something is wrong, as these objects should not be re-hydrated")
    }

    required init() {
        _ = CustomNode._initClass
        super.init () // Compiler error: Property 'self.foo' not initialized at super.init call
    }

    static var _initClass: Void = {
        let className = StringName("CustomNode")
        let classInfo = ClassInfo<CustomNode> (name: className)
    } ()
}
```

And now it looks like this:
```swift
class CustomNode: Node2D {
    let surface = SurfaceTool()
    let edgeMesh = MeshInstance2D()

    var foo: Vector2
    
    override open class var classInitializer: Void {
        let _ = super.classInitializer
        return _initializeClass
    }

    private static var _initializeClass: Void = {
        let className = StringName("CustomNode")
        let classInfo = ClassInfo<CustomNode> (name: className)
    } ()
}
```
I'm not even sure why it compiles at all. I'd much prefer the older implementation, when compiler pointed out initialization errors, as opposed to having runtime crashes.

**Comment by PadraigK** [comment] 2023-11-17 16:51
Wow, that is a weird one. I am able to reproduce it with 

```
class TestNode: Node {
    var hi: String
}
```

so I don't think it is related to the `@Godot` macro or the recent changes there. We must be doing something strange when initializing godot objects in the superclasses I'll keep looking.

**Comment by PadraigK** [comment] 2023-11-17 17:48
I was able to reproduce this with 

```
// in SwiftGodot
`open class MySuperclass {}`

// in something that imports SwiftGodot
class Wat: MySuperclass {
    var hi: String
}
```

**Comment by PadraigK** [comment] 2023-11-17 17:48
I was able to reproduce this with 

```
// in SwiftGodot
`open class MySuperclass {}`

// in something that imports SwiftGodot
class Wat: MySuperclass {
    var hi: String
}
```

**Comment by PadraigK** [comment] 2023-11-17 18:01
https://github.com/apple/swift/issues/69965

**Comment by PadraigK** [comment] 2023-11-17 18:24
> The result should be the same in both cases, since the member is a struct, and has a default initializer (?). 

@koliyo The two cases are different. In the case where a default value is assigned in your class (e.g. `var foo = Vector2()`)  it is working correctly. The bug here is that Swift is building successfully when your code is not setting a default value for the property. It ought to be giving a compile error instead because from `var foo: Vector2` there is no way for Swift to know what the value of `foo` should be, it only knows the type.
 
Here is a boiled down, non SwiftGodot example to demonstrate:

If you try to build this
```swift
class Hi {
    let name: String
}
```

It will (correctly) error with:
```
error: class 'Hi' has no initializers
class Hi {
      ^
note: stored property 'name' without initial value prevents synthesized initializers
```

**Comment by tishin** [comment] 2023-11-17 19:09
@PadraigK I think what you described in the Swift issue is only a part of the problem. With this setup it doesn't let me instantiate `MySubclass`:
```swift
// MyLibrary module
open class MySuperclass {}
```
```swift
import MyLibrary

class MySubclass: MySuperclass {
    var hi: String
}

print(MySubclass().hi) // Compiler error: 'MySubclass' cannot be constructed because it has no accessible initializers
```

And adding required init breaks `MySubclass` compilation:
```swift
// MyLibrary module
open class MySuperclass {
    public required init() {}
}
```
```swift
import MyLibrary

class MySubclass: MySuperclass { // Compiler error: Class 'MySubclass' has no initializers
    var hi: String
}
```

But it's possible to instantiate `SwiftGodot` subclasses with uninitialized properties. There has to be more to it.

**Comment by PadraigK** [comment] 2023-11-17 19:21
I have a workaround for this but I'll be offline for a few hours. Bottom line is making wrapped's internal initializer public, but I'm hoping to clean up some other initializer stuff while I'm here.

**Comment by PadraigK** [comment] 2023-11-18 00:00
@tishin You're right, there's something extra going on. I think it is this: https://github.com/apple/swift/issues/61508

To keep working with our example here:

```swift
// MyLibrary module
open class MySuperclass {
    public required init() {}
    internal init(boop: Bool) {}
}
```

```swift
import MyLibrary

class MySubclass: MySuperclass { 
    var hi: String
}
```

This will compile fine (but ought not to, because it should give a compiler error)

**Comment by Matt-Is-Confused** [comment] 2023-11-19 00:51
#242 seems to be a case where you can compile and run with invalid or uninitialized properties. At runtime all properties will contain invalid data.
Wrapping the Vector2 in a struct will reintroduce the init requirement to compile
```Swift
struct TestStruct {
    var vec: Vector2
    var speed: Float = 500.0
}
var tstr = TestStruct()
```
`Missing argument for parameter 'vec' in call`

**Comment by migueldeicaza** [comment] 2024-07-02 19:05
This was fixed in upstream Swift.

**Closed by migueldeicaza** 2024-07-02 19:05 UTC
