### ISSUE TITLE
Hot reloading doesn't work

### ISSUE THREAD

**Issue by roydbt** [migueldeicaza/SwiftGodot#449] opened 2024-04-06 11:20 UTC
Whenever I build the Swift project, I must restart the Godot project for changes, such as new classes and new `@Callable` methods, to take effect.

**Comment by Nemesisprime** [comment] 2024-04-19 14:43
Related to https://github.com/migueldeicaza/SwiftGodot/issues/433 

I've been kind of looking into it but haven't really had the time/focus yet.

**Comment by migueldeicaza** [comment] 2024-06-16 15:39
This is a duplicate of the other issue.

**Closed by migueldeicaza** 2024-06-16 15:39 UTC

**Comment by daniele-niero** [comment] 2025-05-08 11:03
Hi,

I don't think this is working for Windows. Am I correct?

If I rebuild without closing Godot when I go back to it, it simply crashes
