### ISSUE TITLE
Can't interact with custom controls

### ISSUE THREAD

**Issue by lupuchard** [migueldeicaza/SwiftGodot#198] opened 2023-10-28 19:19 UTC
When I try to make a subclass of a UI control:
```
import Foundation
import SwiftGodot

@Godot
public class TestButton: Button { }
```

I can add it to the scene and it will render as normal like other controls, but mouse events will no longer trigger. This seems to happen for any control type (I tried inheriting from Button, Tree and List).

If I put the custom control inside a ScrollContainer, the scroll bar won't work, but if I put it into a Split or H/VBox container, the other controls in that container do still work.

**Comment by Matt-Is-Confused** [comment] 2023-11-01 19:19
Hey can you check the mouse control setting for your node in the editor. They are under `Control > Mouse > Filter` They look like this 
<img width="265" alt="Screenshot 2023-11-01 at 3 15 28 PM" src="https://github.com/migueldeicaza/SwiftGodot/assets/6394475/03f36513-bddd-4a13-a333-f2ad6533f4b9">
If it isn't a problem with input filtering it could be the binding

**Comment by PadraigK** [comment] 2023-11-02 00:37
Confirmed that this is definitely an issue — as soon as you subclass any Button, it won't call _pressed or emit any signals.

I did some investigating and determined that this generated proxy method is always returning false:

```swift
func _Control_proxy_has_point (instance: UnsafeMutableRawPointer?, args: UnsafePointer<UnsafeRawPointer?>?, retPtr: UnsafeMutableRawPointer?) {
    guard let instance else { return }
    guard let args else { return }
    let swiftObject = Unmanaged<Control>.fromOpaque(instance).takeUnretainedValue()
    let ret = swiftObject._hasPoint (args [0]!.assumingMemoryBound (to: Vector2.self).pointee)
    retPtr!.storeBytes (of: ret, as: Bool.self)
}
```

I think it is returning false because it is calling `_hasPoint` on our subclassed object. That just calls a default implementation in `Control.swift` which returns false, so the text to see if a click is inside the buttons area always fails, and thus the button press is never registered.

As evidence for this theory, adding this override to our Button subclass fixes the issue:
```swift 
override func _hasPoint(_ point: Vector2) -> Bool {
   Rect2(position: .zero, size: getSize()).hasPoint(point: point)
}
``` 

I'm not sure what the solution is. I think either some needed code is not being generated, or some Godot code should be called in `Control.swift` instead of defaulting to `false`?

**Comment by migueldeicaza** [comment] 2023-11-02 00:47
Thank you for this detective work!

So the issue is that we register every method in a subclass as being implemented and dispatch from there.  The reason being that I don’t have a way of detecting if something was overwritten In a subclass without some sort of reflection.

The solution might be to introduce an @override macro that would both override the method and flag the method as implemented (currently, if you look at Godot generated code we generate a big table for each class that always reports “yes, I implement this”).   So we would remove this big chunk of generated code (which is actually suboptimal) with a generated table based on the @override macros.


Sadly, I am traveling this weekend and won’t be back until Tuesday.   But this investigation pointed at the source of the problem (we do have a bug filed here about this, will link later)

**Comment by migueldeicaza** [comment] 2023-11-02 01:56
Additional comments from Slack, before they get deleted:

The issue is that Godot calls us to find out about our overwritten methods, and because we have no way of knowing this, SwiftGodot currently ships a jumbo "We handle it all", here is what this looks like for Control:

```swift
    override class func getVirtualDispatcher (name: StringName) -> GDExtensionClassCallVirtual? {
        switch name.description {
            case "_can_drop_data":
                return _Control_proxy_can_drop_data
            case "_drop_data":
                return _Control_proxy_drop_data
            case "_get_drag_data":
                return _Control_proxy_get_drag_data
            case "_get_minimum_size":
                return _Control_proxy_get_minimum_size
            case "_get_tooltip":
                return _Control_proxy_get_tooltip
            case "_gui_input":
                return _Control_proxy_gui_input
            case "_has_point":
                return _Control_proxy_has_point
            case "_make_custom_tooltip":
                return _Control_proxy_make_custom_tooltip
            case "_structured_text_parser":
                return _Control_proxy_structured_text_parser
            default:
                return super.getVirtualDispatcher (name: name)
        }
        
    }
```

And that ends up calling our default implementation for each method, that returns a default value.   In this particular case, we have a case where Godot is asking us for information "Hey does this looks good to you", and we have told Godot "Yeah, we will handle this", but in reality, we provide a canned answer.

Ideally, we could find at compile time, if a method is being overwritten, or at runtime, if a method is overwritten.   The latter has been done extensively in other frameworks, but comes at a memory and startup cost that always end up having to be moved into some two-stage compilation process anyways (In .NET this was moved to source generators, which is a bit like macros, before it was standardized, every system had to roll their own precompilers).

Lacking this, we are going to have to generate the above method based on the inclusion of the `@override` macro, which would generate the above.

While this is a usability step back, it will reduce the size of SwiftGodot, with 176 fewer dispatcher methods and fewer 2372 proxy methods - we would generate those on demand for each type.

**Comment by PadraigK** [comment] 2023-11-02 18:07
Here's one proposal where we could use the existing @Godot macro:

https://gist.github.com/PadraigK/995be44922778aa5298f60b4ac551fa2

**Comment by migueldeicaza** [comment] 2023-11-02 21:04
On the channel we are exploring a few options:

* Extending the @Godot macro
* Leveraging the "Runtime" library to determine if a method is overwritten
* Using dlsym to lookup a known function name and figure out if we have an overwritten version

**Comment by migueldeicaza** [comment] 2023-11-08 20:06
I will integrate the ideas that were put together on the channel into the Godot macro:

https://github.com/migueldeicaza/SwiftGodot/issues/217

**Comment by migueldeicaza** [comment] 2023-11-09 14:47
A proper fix has been committed now.

**Closed by migueldeicaza** 2023-11-09 14:47 UTC
